image: docker:latest
services:
- docker:dind

stages:
- build

build:
  stage: build
  script:
    - docker build --build-arg HTTP_PROXY="http://10.10.12.38:3128" --build-arg HTTPS_PROXY="http://10.10.12.38:3128" -t test/vueapp .

